spring.application.name=Spa-Tarea
# ===============================
# CONFIGURACIÓN DE BASE DE DATOS (MySQL)
# ===============================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:8080/SpaTarea?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# ===============================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# ===============================
server.port=8080